---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# prettysurvey

<!-- badges: start -->
<!-- badges: end -->

The goal of prettysurvey is to generate streamlined output from the `survey` package, with an application to NCHS data.


## Installation

You can install the development version of prettysurvey like so:

``` r
install.packages(c("git2r", "remotes"))

# If you are re-installing it, first remove it:
remove.packages("prettysurvey")

# On local computer
remotes::install_git(
	url = "https://git.biotech.cdc.gov/kpr9/prettysurvey"
	, git = "git2r"
	, upgrade = "never")

# On EDAV RStudio
remotes::install_git(
	url = "https://git.biotech.cdc.gov/kpr9/prettysurvey"
	, upgrade = "never")

```

## Example

This is a basic example:

```{r example}
library(prettysurvey)
tab(namcs2019, "AGER")
```
